# Generated by Django 5.2.17 on 2026-09-30 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColunaLida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField()),
                ('pagina', models.PositiveIntegerField()),
                ('tabela', models.CharField(blank=True, max_length=300)),
                ('coluna', models.CharField(blank=True, max_length=200)),
                ('ocorrencia', models.PositiveIntegerField(default=0, help_text='Qual aparição deste registro no documento (condição)')),
                ('registro_ans', models.CharField(blank=True, max_length=9)),
                ('plano_ans', models.JSONField(blank=True, null=True)),
                ('achados', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('ignorada', 'Ignorada')], default='pendente', max_length=20)),
            ],
            options={
                'ordering': ['documento', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('nome_original', models.CharField(max_length=255)),
                ('serie', models.CharField(blank=True, help_text='Mesmo material em versões diferentes (ex.: allcare_unimed_bh_adesao_mg)', max_length=200)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('url_origem', models.URLField(blank=True, max_length=500)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('em_revisao', 'Em revisão'), ('publicado', 'Publicado'), ('descartado', 'Descartado'), ('erro', 'Erro')], default='processando', max_length=20)),
                ('paginas', models.PositiveIntegerField(default=0)),
                ('ocr', models.BooleanField(default=False)),
                ('leitura_llm', models.CharField(default='nenhuma', help_text='nenhuma | ao_vivo | gravada', max_length=20)),
                ('custo_llm_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('operadora', models.CharField(blank=True, max_length=200)),
                ('administradora', models.CharField(blank=True, max_length=200)),
                ('tipo_contratacao', models.CharField(blank=True, max_length=40)),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('resumo', models.JSONField(blank=True, default=dict)),
                ('achados_documento', models.JSONField(blank=True, default=list)),
                ('extra_llm', models.JSONField(blank=True, default=dict, help_text='coparticipação, carências, elegibilidade, avisos')),
                ('erro', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('tipo', models.CharField(choices=[('dados_ans', 'Dados abertos da ANS'), ('site_operadora', 'Site público da operadora'), ('pdf_operadora', 'Material da operadora'), ('pdf_administradora', 'Material de administradora'), ('envio_corretor', 'Enviado por corretor'), ('parceria', 'Integração com parceiro')], max_length=30)),
                ('url', models.URLField(blank=True)),
                ('confiabilidade', models.PositiveSmallIntegerField(default=3, help_text='1 (baixa) a 5 (fonte oficial)')),
                ('observacoes', models.TextField(blank=True, help_text='robots.txt, termos de uso, contato')),
            ],
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ans', models.CharField(max_length=6, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('cancelada_em', models.DateField(blank=True, null=True)),
                ('motivo_cancelamento', models.CharField(blank=True, max_length=200)),
                ('no_cotador', models.BooleanField(default=False, help_text='Aparece na lista de operadoras do Cotador')),
            ],
        ),
        migrations.CreateModel(
            name='CelulaLida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.CharField(max_length=5)),
                ('valor_geometrico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_llm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_leitura', models.CharField(max_length=20)),
                ('caixa', models.JSONField(blank=True, help_text='[x0, topo, x1, base] em pontos do PDF', null=True)),
                ('revisar', models.BooleanField(default=False)),
                ('corrigida', models.BooleanField(default=False)),
                ('coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celulas', to='radar.colunalida')),
            ],
            options={
                'ordering': ['coluna', 'faixa'],
            },
        ),
        migrations.AddField(
            model_name='colunalida',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colunas', to='radar.documento'),
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tabela_nova', 'Tabela nova'), ('reajuste', 'Preço alterado'), ('produto_novo', 'Produto novo'), ('produto_removido', 'Produto saiu da tabela'), ('fonte_divergente', 'Fontes divergentes'), ('registro_invalido', 'Registro ANS inválido'), ('plano_suspenso', 'Plano suspenso ou cancelado na ANS'), ('operadora_cancelada', 'Operadora cancelada na ANS'), ('preco_fora_da_banda', 'Preço fora da banda da nota técnica'), ('vigencia_vencida', 'Vigência vencida')], max_length=30)),
                ('severidade', models.CharField(default='info', max_length=10)),
                ('titulo', models.CharField(max_length=300)),
                ('detalhe', models.JSONField(blank=True, default=dict)),
                ('registro_ans', models.CharField(blank=True, max_length=9)),
                ('operadora', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('data_efeito', models.DateField(blank=True, null=True)),
                ('resolvido', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='radar.documento')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='fonte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radar.fonte'),
        ),
        migrations.CreateModel(
            name='TabelaPublicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ans', models.CharField(db_index=True, max_length=9)),
                ('ocorrencia', models.PositiveIntegerField(default=0)),
                ('condicao', models.CharField(blank=True, max_length=300)),
                ('nome_plano', models.CharField(blank=True, max_length=300)),
                ('operadora', models.CharField(blank=True, max_length=200)),
                ('administradora', models.CharField(blank=True, max_length=200)),
                ('tipo_contratacao', models.CharField(blank=True, max_length=40)),
                ('precos', models.JSONField(help_text='faixa -> valor')),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('publicada_em', models.DateTimeField(auto_now_add=True)),
                ('confirmada_em', models.DateTimeField(blank=True, help_text='Última vez que um documento novo trouxe os mesmos preços', null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('coluna', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='radar.colunalida')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicacoes', to='radar.documento')),
                ('fonte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radar.fonte')),
                ('substituida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radar.tabelapublicada')),
            ],
            options={
                'ordering': ['registro_ans', 'ocorrencia', '-versao'],
                'indexes': [models.Index(fields=['registro_ans', 'ativa'], name='radar_tabel_registr_77b0d9_idx')],
            },
        ),
    ]
