# Generated by Django 5.2.17 on 2026-09-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_versao',
            field=models.DateField(blank=True, help_text='Data desta versão do material (nome do arquivo, capa)', null=True),
        ),
    ]
