# Generated by Django 5.2.17 on 2026-09-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0002_documento_data_versao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='leitura_llm',
            field=models.CharField(default='nenhuma', help_text='nenhuma | ao_vivo | gravada | falhou', max_length=20),
        ),
    ]
