# Generated by Django 5.2.17 on 2026-09-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0003_leitura_llm_falhou'),
    ]

    operations = [
        migrations.AddField(
            model_name='colunalida',
            name='marcas_condicao',
            field=models.JSONField(blank=True, default=list, help_text='Condição de venda lida no título e no rótulo: vidas, coparticipação, composição...'),
        ),
        migrations.AddField(
            model_name='tabelapublicada',
            name='marcas_condicao',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='colunalida',
            name='ocorrencia',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de aparição do registro no documento; desempata quando a condição não distingue'),
        ),
    ]
