# Generated by Django 5.2.17 on 2026-09-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_marcas_de_condicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('tabela_nova', 'Tabela nova'), ('reajuste', 'Preço alterado'), ('produto_novo', 'Produto novo'), ('produto_removido', 'Produto saiu da tabela'), ('condicao_alterada', 'Condição de venda mudou'), ('fonte_divergente', 'Fontes divergentes'), ('registro_invalido', 'Registro ANS inválido'), ('plano_suspenso', 'Plano suspenso ou cancelado na ANS'), ('operadora_cancelada', 'Operadora cancelada na ANS'), ('preco_fora_da_banda', 'Preço fora da banda da nota técnica'), ('vigencia_vencida', 'Vigência vencida')], max_length=30),
        ),
    ]
