# Generated by Django 5.2.17 on 2026-10-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0005_evento_condicao_alterada'),
    ]

    operations = [
        migrations.AddField(
            model_name='celulalida',
            name='valor_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recalculado pelo percentual de faixa das colunas com o mesmo padrão', max_digits=10, null=True),
        ),
    ]
