# Generated by Django 5.2.17 on 2026-10-01 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0006_valor_calculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fonte',
            name='coleta',
            field=models.CharField(choices=[('manual', 'Manual (upload)'), ('pagina_publica', 'Página pública com links'), ('url_direta', 'Endereço fixo do material')], default='manual', help_text='Como a fonte é capturada; cada tipo é uma classe do pacote coletor', max_length=30),
        ),
        migrations.AddField(
            model_name='fonte',
            name='coleta_ativa',
            field=models.BooleanField(default=False, help_text='Entra na coleta agendada'),
        ),
        migrations.AddField(
            model_name='fonte',
            name='config_coleta',
            field=models.JSONField(blank=True, default=dict, help_text='Endereço, filtros, onde está a data da versão... (ver o tipo de captura)'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('tabela_nova', 'Tabela nova'), ('reajuste', 'Preço alterado'), ('produto_novo', 'Produto novo'), ('produto_removido', 'Produto saiu da tabela'), ('versao_coletada', 'Tabela coletada'), ('coleta_falhou', 'Coleta com problema'), ('condicao_alterada', 'Condição de venda mudou'), ('fonte_divergente', 'Fontes divergentes'), ('registro_invalido', 'Registro ANS inválido'), ('plano_suspenso', 'Plano suspenso ou cancelado na ANS'), ('operadora_cancelada', 'Operadora cancelada na ANS'), ('preco_fora_da_banda', 'Preço fora da banda da nota técnica'), ('vigencia_vencida', 'Vigência vencida')], max_length=30),
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('terminada_em', models.DateTimeField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('rodando', 'Rodando'), ('ok', 'Concluída'), ('bloqueada', 'Bloqueada pelo robots.txt'), ('erro', 'Com erro')], default='rodando', max_length=20)),
                ('encontrados', models.PositiveIntegerField(default=0)),
                ('novos', models.PositiveIntegerField(default=0)),
                ('conhecidos', models.PositiveIntegerField(default=0, help_text='Baixados, mas já estavam no acervo (mesmo hash)')),
                ('sem_mudanca', models.PositiveIntegerField(default=0)),
                ('bloqueados', models.PositiveIntegerField(default=0)),
                ('erros', models.JSONField(blank=True, default=list)),
                ('mensagem', models.CharField(blank=True, max_length=300)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coletas', to='radar.fonte')),
            ],
            options={
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemColetado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('chave_serie', models.CharField(blank=True, max_length=500)),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('etag', models.CharField(blank=True, max_length=200)),
                ('modificado_em', models.CharField(blank=True, max_length=100)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('situacao', models.CharField(blank=True, max_length=60)),
                ('visto_primeiro_em', models.DateTimeField(auto_now_add=True)),
                ('visto_por_ultimo_em', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radar.documento')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_coletados', to='radar.fonte')),
            ],
            options={
                'unique_together': {('fonte', 'url')},
            },
        ),
    ]
