# Generated by Django 5.2.17 on 2026-10-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0010_evento_rede_alterada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('tabela_nova', 'Tabela nova'), ('reajuste', 'Preço alterado'), ('produto_novo', 'Produto novo'), ('produto_removido', 'Produto saiu da tabela'), ('versao_coletada', 'Tabela coletada'), ('versao_historica', 'Versão antiga no histórico'), ('coleta_falhou', 'Coleta com problema'), ('condicao_alterada', 'Condição de venda mudou'), ('fonte_divergente', 'Fontes divergentes'), ('registro_invalido', 'Registro ANS inválido'), ('plano_suspenso', 'Plano suspenso ou cancelado na ANS'), ('operadora_cancelada', 'Operadora cancelada na ANS'), ('rede_alterada', 'Rede hospitalar alterada'), ('preco_fora_da_banda', 'Preço fora da banda da nota técnica'), ('vigencia_vencida', 'Vigência vencida'), ('nota_tecnica_nova', 'Nota técnica nova na ANS')], max_length=30),
        ),
    ]
