# Generated by Django 5.2.17 on 2026-10-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0011_evento_nota_tecnica_nova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captura',
            name='tipo',
            field=models.CharField(choices=[('pagina_publica', 'Página pública com links'), ('url_direta', 'Endereço fixo do material'), ('api_json', 'API pública (JSON)'), ('wayback', 'Histórico no arquivo da web'), ('caixa_email', 'Caixa de e-mail')], help_text='Cada tipo é uma classe do pacote coletor', max_length=30),
        ),
    ]
