# Generated by Django 5.2.17 on 2026-10-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0012_captura_api_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='operadora',
            name='canal',
            field=models.CharField(blank=True, help_text='Por onde o preço chega, segundo o mapeamento (fontes/operadoras)', max_length=200),
        ),
        migrations.AddField(
            model_name='operadora',
            name='relatorio',
            field=models.CharField(blank=True, help_text='Relatório do mapeamento no repositório', max_length=200),
        ),
    ]
